MVCEmp/Controllers/SystemDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCEmp.Models;
using System.Data;
using System.IO;
using NPOI.SS.UserModel;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;


namespace MVCEmp.Controllers
{
    public class SystemDetailController : Controller
    {
        SystemDetailModels sdModels = new SystemDetailModels();
        App_Start.ClassDataBase dbClass = new App_Start.ClassDataBase();

        // GET: /SystemDetail/
        public ActionResult Index(SystemDetailModels viewModel)
        {
            GetBindData("", "1", viewModel);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(FormCollection form, SystemDetailModels viewModel)
        {
            string funSearchValue = form["searchValue"].ToString();
            string funPageIndex = form["hidePageIndex"].ToString();
            GetBindData(funSearchValue, funPageIndex, viewModel);
            return View(viewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public RedirectResult Create(FormCollection form)
        {
            List<string> listPostData = new List<string>();
            listPostData.Add(form["textSystemData"].ToString());
            listPostData.Add(form["textSystemValue"].ToString());
            listPostData.Add(form["textSystemTitle"].ToString());
            listPostData.Add(form["textSystemNotation"].ToString());
            listPostData.Add(form["textSystemRemark"].ToString());
            listPostData.Add(form["hideSystemStatus"].ToString());
            ViewBag.valShowDetail = sdModels.DataCreate(listPostData);
            return Redirect("~/SystemDetail/Index");
        }

        public ActionResult Update(string cl, string vl)
        {
            ViewBag.valSystemClass = cl.ToString();
            ViewBag.valSystemValue = vl.ToString();
            List<listSystemDetail> detailListSystem = sdModels.detailListSystemDetail(cl, vl);
            ViewBag.valSystemTitle = detailListSystem[0].lSystemTitle.ToString();
            ViewBag.valSystemNotation = detailListSystem[0].lSystemNotation.ToString();
            ViewBag.valSystemRemark = detailListSystem[0].lSystemRemark.ToString();
            ViewBag.valSystemStatus = detailListSystem[0].lSystemStatus.ToString();
            return View();
        }

        [HttpPost]
        public RedirectResult Update(FormCollection form)
        {
            List<string> listPostData = new List<string>();
            listPostData.Add(form["hideSystemClass"].ToString());
            listPostData.Add(form["hideSystemValue"].ToString());
            listPostData.Add(form["textSystemTitle"].ToString());
            listPostData.Add(form["textSystemNotation"].ToString());
            listPostData.Add(form["textSystemRemark"].ToString());
            listPostData.Add(form["hideSystemStatus"].ToString());
            string fReturnValue = sdModels.DataUpdate(listPostData);
            return Redirect("~/SystemDetail/Index");
        }

        public RedirectResult Delete(string vClass, string vValue)
        {
            string valClass, valValue, returnExecuteValue;
            valClass = Request["cl"].ToString();
            valValue = Request["vl"].ToString();
            returnExecuteValue = sdModels.DataDelete(valClass, valValue);
            return Redirect("~/SystemDetail/Index");
        }

        [HttpPost]
        public void UpLoad(HttpPostedFileBase fileUpload)
        {
            string showDetailData = ""; DataTable dtSystemDetail = new DataTable();
            if (fileUpload != null && fileUpload.ContentLength > 0)
            {
                string FilePath = System.Web.HttpContext.Current.Server.MapPath("~/excel");
                string FileName = fileUpload.FileName;
                fileUpload.SaveAs(string.Format(@"{0}\{1}", FilePath, FileName));
                dynamic hssfweb; DataTable tempDataTable = new DataTable(); tempDataTable.Clear();
                using (MemoryStream ms = new MemoryStream(dbClass.getFileToRead(string.Format(@"{0}\{1}", FilePath, FileName))))
                {
                    hssfweb = WorkbookFactory.Create(ms);
                }
                ISheet sheet = (ISheet)hssfweb.GetSheetAt(0);
                if (sheet.LastRowNum > 0)
                {
                    IRow rowT = (IRow)sheet.GetRow(0);
                    for (int i = 0; i < 6; i++)
                    {
                        DataColumn col = new DataColumn(rowT.GetCell(i).ToString(), typeof(string));
                        tempDataTable.Columns.Add(col);
                    }
                    for (int i = 1; i <= sheet.LastRowNum; i++)
                    {
                        IRow rowD = (IRow)sheet.GetRow(i);
                        if (rowD != null)
                        {
                            DataRow tempRow = tempDataTable.NewRow();
                            for (int a = 0; a < 6; a++)
                            {
                                tempRow[a] = (rowD.GetCell(a).ToString() != null) ? rowD.GetCell(a).ToString() : "";
                            }
                        }
                    }
                    List<listSystemDetail> SystemDetailList = sdModels.reListSystemDetail();
                    string valSystemClass, valSystemValue, valSystemTitle, valSystemNotation, valSystemRemark, valSystemStatus;
                    if (tempDataTable.Rows.Count > 0)
                    {
                        foreach (DataRow drtemp in tempDataTable.Rows)
                        {
                            List<string> DataList = new List<string>();
                            DataList.Add(drtemp["SystemClass"].ToString());
                            DataList.Add(drtemp["SystemValue"].ToString());
                            DataList.Add(drtemp["SystemTitle"].ToString());
                            DataList.Add(drtemp["SystemNotation"].ToString());
                            DataList.Add(drtemp["SystemRemark"].ToString());
                            DataList.Add(drtemp["SystemStatus"].ToString());
                            valSystemClass = drtemp["SystemClass"].ToString();
                            valSystemValue = drtemp["SystemValue"].ToString();
                            if (SystemDetailList.Where(x => x.lSystemClass == valSystemClass && x.lSystemValue == valSystemValue).Count() > 0)
                            {
                                sdModels.DataUpdate(DataList);
                            }
                            else
                            {
                                sdModels.DataUpdate(DataList);
                            }
                        }
                    }
                    List<listSystemDetail> SysDetailList = new List<listSystemDetail>();
                    if (SysDetailList.Count > 0)
                    {
                        foreach (listSystemDetail item in SysDetailList)
                        {
                            showDetailData += string.Format(@"{0}~{1}~{2}~{3}~{4}~{5},br />"
                                , item.lSystemClass, item.lSystemValue, item.lSystemTitle, item.lSystemNotation, item.lSystemRemark, item.lSystemStatus);
                        }
                    }
                }
            }
            Response.Write(showDetailData);
        }

        [HttpPost]
        public void OutExcelData()
        {
            string ExportFileName = "SystemData.xlsx"; string ExportFileTitle = "Data";
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            XSSFWorkbook NpoiWB = new XSSFWorkbook();
            XSSFCellStyle xCellStyle = (XSSFCellStyle)NpoiWB.CreateCellStyle();
            XSSFDataFormat NpoiFormat = (XSSFDataFormat)NpoiWB.CreateDataFormat();
            xCellStyle.SetDataFormat(NpoiFormat.GetFormat("[DbNum2][$-804]0"));
            XSSFCellStyle cellStyleFontColor = (XSSFCellStyle)NpoiWB.CreateCellStyle();
            XSSFFont font1 = (XSSFFont)NpoiWB.CreateFont(); font1.Color = (short)10; font1.IsBold = true;
            cellStyleFontColor.SetFont(font1);
            ISheet xSheet = NpoiWB.CreateSheet(ExportFileTitle);
            List<string> listColumn = new List<string>() { "SystemClass", "systemValue", "SystemTitle", "SystemNotation", "SystemRemark", "SystemStatus" };
            IRow xRowT = xSheet.CreateRow(0); xRowT.HeightInPoints = 40;
            for (int i = 0; i < listColumn.Count; i++)
            {
                ICell xCellT = xRowT.CreateCell(i);
                xCellT.SetCellValue(listColumn[i]);
            }
            List<listSystemDetail> systemDetailList = new List<listSystemDetail>();
            systemDetailList = sdModels.reListSystemDetail();
            for (int i = 0; i < systemDetailList.Count; i++)
            {
                listSystemDetail dr = systemDetailList[i];
                List<string> listData = new List<string>();
                listData.Add(dr.lSystemClass.ToString());
                listData.Add(dr.lSystemValue.ToString());
                listData.Add(dr.lSystemTitle.ToString());
                listData.Add(dr.lSystemNotation.ToString());
                listData.Add(dr.lSystemRemark.ToString());
                listData.Add(dr.lSystemStatus.ToString());
                IRow xRowD = xSheet.CreateRow(i + 1);
                xRowD.HeightInPoints = 40;
                for (int b = 0; b < listData.Count; b++)
                {
                    ICell xCellData = xRowD.CreateCell(b);
                    xCellData.SetCellValue(listData[b]);
                }

MVCEmp/Views/SystemDetail/Create.cshtml
@using MVCEmp.Models
@model SystemDetailModels
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">

    $(function ($) {
        $('#checkSystemStatus').click(formCheckBox);
        $('btnFormC').click(formCheckData);
    });

    formCheckBox = function () {
        if ($('#checkSystemStatus').prop('checked') == true) {
            $('#hideSystemStatus').val("O");
        } else {
            $('#hideSystemStatus').val("X");
        }
    }

    formCheckData = function () {
        if ($('#textSystemClass').val() == "") { $('showMess').notify("系統類別不得空白!!"); $('textSystemClass').focus(); return false; }
        if ($('#textSystemValue').val() == "") { $('showMess').notify("系統參數值不得空白!!"); $('textSystemValue').focus(); return false; }
        if ($('#textSystemTitle').val() == "") { $('showMess').notify("系統標題不得空白!!"); $('textSystemTitle').focus(); return false; }
    }

</script>
<h2>Create</h2>
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form1" }))
{
    @Html.Hidden("hideSystemStatus", "")
    <table style="width:800px; text-align:center;font-size:15px;font-weight:bold" border="0" cellpadding="0" cellspacing="0">
        <tr style="height:40px; font-weight:bold; font-size:24px"><td style="width:100%; text-align:center" colspan="4">新增系統參數</td></tr>
        <tr style="height:40px">
            <td style="width:100px; text-align:left">系統類別</td>
            <td style="width:300px; text-align:left">@Html.TextBox("textSystemClass", (string)ViewBag.valSystemClass, new { Style = "width:80%; height:30px" })</td>
            <td style="width:100px; text-align:left">系統數值</td>
            <td style="width:300px; text-align:left">@Html.TextBox("textSystemValue", "", new { Style = "width:80%; height:30px" })</td>
        </tr>
        <tr style="height:40px">
            <td style="width:100px; text-align:left">系統類別</td>
            <td style="width:700px; text-align:left" colspan="3">@Html.TextBox("textSystemTitle", "", new { Style = "width:100%; height:30px" })</td>
        </tr>
        <tr style="height:40px">
            <td style="width:100px; text-align:left">系統說明</td>
            <td style="width:300px; text-align:left">@Html.TextArea("textSystemNotation", "", 10, 200, new { Style = "width:100%" })</td>
            <td style="width:100px; text-align:left">系統備註</td>
            <td style="width:300px; text-align:left">@Html.TextArea("textSystemRemark", "", 10, 200, new { Style = "width:100%" })</td>
        </tr>
        <tr style="height:40px">
            <td style="width:100px; text-align:left">開放使用</td>
            <td style="width:300px; text-align:left">@Html.CheckBox("checkSystemStatus", false) 可使用</td>
            <td style="width:400px; text-align:left" colspan="2"><span id="showMess">@ViewBag.valShowDetail</span></td>
        </tr>
        <tr style="height:40px">
            <td style="width:100%; text-align:center" colspan="4">
                <input type="submit" id="btmFormC" value="Create" />
            </td>
        </tr>
    </table>
}

MVCEmp/Views/SystemDetail/Index.cshtml
@using MVCEmp.Models
@model SystemDetailModels
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Index", "SystemDetail", FormMethod.Post, new { id = "form1", enctype = "multipart/form-data" }))
{
    <table style="width:900px; text-align:center" border="0" cellpadding="0" cellspacing="0">
        <tr style="height:40px;font-size:20px;font-weight:bold"><td style="width:100%; text-align:center" colspan="4">系統參數資料檔<hr /></td></tr>
        <tr style="height:35px; color:black">
            <td style="width:800px; text-align:left">
                關鍵字 : @Html.TextBox("searchValue", (string)ViewBag.searchValue, new { Style = "width:600px; height:35px" })
                <input type="submit" id="btnsubmit" value="查詢" style="width:100px; height:30px;font-weight:bold;font-size:18px" />
            </td>                
            <td style="width:100px; text-align:right">@Html.ActionLink("新增系統參數", "Create", "SystemDetail", new { Style="height:35px; font-size:16px" })</td>
        </tr>
        <tr><td style="width:100%" colspan="4"><hr /></td></tr>
        <tr><td style="width:100%" colspan="4">@{Html.RenderPartial("List", Model);}</td></tr>
    </table>
}

MVCEmp/Views/SystemDetail/List.cshtml
@using MVCEmp.Models
@model SystemDetailModels
@{ Layout = null; }

<script type="text/javascript">

    FormPageFirst = function () { $('#hidePageIndex').val('1'); $('#form1').submit(); }
    FormPageFinal = function () { $('#hidePageIndex').val($('#hidePageCount').val()); $('#form1').submit(); }
    FormPagePrev = function () { $('#hidePageIndex').val(eval(eval($('#hidePageIndex').val()) - 1)); $('#form1').submit(); }
    FormPageNext = function () { $('#hidePageIndex').val(eval(eval($('#hidePageIndex').val()) + 1)); $('#form1').submit(); }
    FormPageSelect = function (newPageIndex) { $('#hidePageIndex').val(newPageIndex); $('#form1').submit(); }

</script>
@Html.Hidden("hideDataCount", (string)ViewBag.valSumDataCount)
@Html.Hidden("hideRowPage", (string)ViewBag.valPageDataCount)
@Html.Hidden("hidePageCount", (string)ViewBag.valSumPageCount)
@Html.Hidden("hidePageIndex", (string)ViewBag.valPageIndex)
@{  int DataIndexTop = 0;
  if (Convert.ToInt32(ViewBag.valPageIndex) > 1) { DataIndexTop = Convert.ToInt32(Convert.ToInt32(ViewBag.valPageDataCount) * Convert.ToInt32(Convert.ToInt32(ViewBag.valPageIndex) - 1)); }
  int DataIndexDown = 0;
  if (Convert.ToInt32(ViewBag.valPageIndex) == 1)
  {
      if (Convert.ToInt32(ViewBag.valSumDataCount) < Convert.ToInt32(ViewBag.valPageDataCount))
      {
          DataIndexDown = Convert.ToInt32(ViewBag.valSumDataCount);
      }
      else
      {
          DataIndexDown = Convert.ToInt32(ViewBag.valPageDataCount);
      }
  }
  else
  {
      if (Convert.ToInt32(Convert.ToInt32(ViewBag.valPageDataCount) * Convert.ToInt32(ViewBag.valPageIndex)) > Convert.ToInt32(ViewBag.valSumDataCount))
      {
          DataIndexDown = Convert.ToInt32(ViewBag.valSumDataCount);
      }
      else
      {
          DataIndexDown = Convert.ToInt32(Convert.ToInt32(ViewBag.valPageDataCount) * Convert.ToInt32(ViewBag.valPageIndex));
      }
  }
}
<table style="width:100%;" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td style="width:100%;" colspan="9">
            頁數: @ViewBag.valPageIndex 頁 / @ViewBag.valSumPageCount 頁
            <input type="submit" id="PageFirst" value="第一頁" style="width:70px; height:35px"
                   @if (Convert.ToInt32(ViewBag.valPageIndex) == 1) { @Html.Raw("disabled") ; } else { @Html.Raw("") ; @Html.Raw("onclick='FormPageFirst()'") ; } />
            <input type="submit" id="PagePrev" value="上一頁" style="width:70px; height:35px"
                   @if (Convert.ToInt32(ViewBag.valPageIndex) == 1) { @Html.Raw("disabled")  ; } else { @Html.Raw("")  ; @Html.Raw("onclick='FormPagePrev()'")  ; } />
            <select id="PageSelect" style="width:70px; height:35px" onchange="FormPageSelect(this.value);">
                @for (int i = 1; i <= Convert.ToInt32((string)ViewBag.valSumPageCount); i++) {
                    <option value="@i.ToString()" @Html.Raw((Convert.ToInt32(ViewBag.valPageIndex) == Convert.ToInt32(i)) ? "selected" : "")>@i.ToString()</option>
                }
            </select>
            <input type="submit" id="PageNext" value="下一頁" style="width:70px; height:35px"
                   @if (Convert.ToInt32(ViewBag.valPageIndex) == Convert.ToInt32(ViewBag.valSumPageCount)) { @Html.Raw("disabled")  ; } else { @Html.Raw("")  ; @Html.Raw("onclick='FormPageNext()'")  ; } />
            <input type="submit" id="PageFinal" value="最末頁" style="width:70px; height:35px"
                   @if (Convert.ToInt32(ViewBag.valPageIndex) == Convert.ToInt32(ViewBag.valSumPageCount)) { @Html.Raw("disabled")   ; } else { @Html.Raw("")   ; @Html.Raw("onclick='FormPageFinal()'")   ; } />
            資料數: 共 @ViewBag.valSumDataCount 筆 / 每頁 @ViewBag.valPageDataCount 筆  / @DataIndexTop ~ @DataIndexDown
        </td>
    </tr>
    <tr><td style="width:100%" colspan="9"><hr /></td></tr>
    <tr style="height:35px; color:white;font-size:18px; background-color:blue">        
        <td style="width:150px; text-align:center">類別</td>
        <td style="width:100px; text-align:center">參數值</td>
        <td style="width:150px; text-align:center">標題</td>
        <td style="width:150px; text-align:center">說明</td>
        <td style="width:150px; text-align:center">備註</td>
        <td style="width:50px; text-align:center">狀態</td>
        <td style="width:100px; text-align:center" colspan="2">更新</td>
    </tr>
    <tr><td colspan="9"><hr /></td></tr>    
    @for (int i = DataIndexTop; i < DataIndexDown; i++)
    {
        <tr style="height:30px;color:blue;font-size:14px;">            
            <td style="width:150px; text-align:center">@Model.listSystemDetail[i].lSystemClass.ToString()</td>
            <td style="width:100px; text-align:center">@Model.listSystemDetail[i].lSystemValue.ToString()</td>
            <td style="width:150px; text-align:center">@Model.listSystemDetail[i].lSystemTitle.ToString()</td>
            <td style="width:175px; text-align:center">@Model.listSystemDetail[i].lSystemNotation.ToString()</td>
            <td style="width:175px; text-align:center">@Model.listSystemDetail[i].lSystemRemark.ToString()</td>
            <td style="width:50px; text-align:center">@Model.listSystemDetail[i].lSystemStatus.ToString()</td>
            <td style="width:50px; text-align:center">@Html.ActionLink("修改", "Update", "SystemDetail", new { cl = Model.listSystemDetail[i].lSystemClass, vl = Model.listSystemDetail[i].lSystemValue }, new AjaxOptions { HttpMethod = "POST" })</td>
            <td style="width:50px; text-align:center">@Html.ActionLink("刪除", "Delete", "SystemDetail", new { cl = Model.listSystemDetail[i].lSystemClass, vl = Model.listSystemDetail[i].lSystemValue }, new AjaxOptions { HttpMethod = "POST" })</td>
        </tr>
        <tr><td style="width:100%" colspan="9"><hr /></td></tr>
    }
</table>


MVCEmp/Views/SystemDetail/Update.cshtml


@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">

    $(function ($) {
        $('#checkSystemStatus').click(formCheckBox);
        $('btnFormC').click(formCheckData);
    });

    formCheckBox = function () {
        if ($('#checkSystemStatus').prop('checked') == true) {
            $('#hideSystemStatus').val("O");
        } else {
            $('#hideSystemStatus').val("X");
        }
    }

    formCheckData = function () {
        if ($('#textSystemTitle').val() == "") { $('showMess').notify("系統標題不得空白!!"); $('textSystemTitle').focus(); return false; }
    }

</script>
<h2>Update</h2>
@using (Html.BeginForm("Update", "SystemDetail", FormMethod.Post, new { id = "form1" }))
{
    @Html.Hidden("hideSystemStatus", (string)ViewBag.valSystemStatus)
    @Html.Hidden("hideSystemClass", (string)ViewBag.valSystemClass)
    @Html.Hidden("hideSystemValue", (string)ViewBag.valSystemValue)
    <table style="width:800px; text-align:center;font-size:15px;font-weight:bold" border="0" cellpadding="0" cellspacing="0">
        <tr style="height:40px; font-weight:bold; font-size:24px"><td style="width:100%; text-align:center" colspan="4">修改系統參數</td></tr>
        <tr style="height:40px">
            <td style="width:100px; text-align:left">系統類別</td>
            <td style="width:300px; text-align:left">@ViewBag.valSystemClass)</td>
            <td style="width:100px; text-align:left">系統數值</td>
            <td style="width:300px; text-align:left">@ViewBag.valSystemValue)</td>
        </tr>
        <tr style="height:40px">
            <td style="width:100px; text-align:left">系統類別</td>
            <td style="width:700px; text-align:left" colspan="3">@Html.TextBox("textSystemTitle", (string)ViewBag.valSystemTitle, new { Style = "width:100%; height:30px" })</td>
        </tr>
        <tr style="height:40px">
            <td style="width:100px; text-align:left">系統說明</td>
            <td style="width:300px; text-align:left">@Html.TextArea("textSystemNotation", (string)ViewBag.valSystemNotation, 10, 200, new { Style = "width:100%" })</td>
            <td style="width:100px; text-align:left">系統備註</td>
            <td style="width:300px; text-align:left">@Html.TextArea("textSystemRemark", (string)ViewBag.valSystemRemark, 10, 200, new { Style = "width:100%" })</td>
        </tr>
        <tr style="height:40px">
            <td style="width:100px; text-align:left">開放使用</td>
            <td style="width:300px; text-align:left">@Html.CheckBox("checkSystemStatus", ((string)ViewBag.valSystemStatus == "O") ? true : false) 可使用</td>
            <td style="width:400px; text-align:left" colspan="2"><span id="showMess">@ViewBag.valShowDetail</span></td>
        </tr>
        <tr style="height:40px">
            <td style="width:100%; text-align:center" colspan="4">
                <input type="submit" id="btmFormC" value="Update" />
            </td>
        </tr>
    </table>
}