MVCEmp/Controllers/EmployeeJobDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCEmp.Models;
using System.Data;

namespace MVCEmp.Controllers
{
    public class EmployeeJobDetailController : Controller
    {
        EmployeeJobDetailModels jdModel = new EmployeeJobDetailModels();
        EmployeeDetailModels edModel = new EmployeeDetailModels();
        SystemDetailModels sdModel = new SystemDetailModels();
        App_Start.ClassDataBase dbClass = new App_Start.ClassDataBase();
        List<listEmployeeDetail> edDetail = new List<listEmployeeDetail>();
        List<listEmployeeJobDetail> jobList = new List<listEmployeeJobDetail>();

        // GET: EmployeeJobDetail
        public ActionResult Index(EmployeeJobDetailModels viewModel)
        {
            getBindData("", "1", viewModel);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(FormCollection form, EmployeeJobDetailModels viewModel)
        {
            string funSearchValue = form["searchValue"].ToString();
            string funPageIndex = form["hidePageIndex"].ToString();
            getBindData(funSearchValue, funPageIndex, viewModel);
            return View(viewModel);
        }

        public ActionResult Create()
        {
            var selEmpData = new List<SelectListItem>();
            selEmpData = edModel.selEmpDataList();
            ViewBag.selEmpData = selEmpData;
            ViewBag.valNowDateTime = System.DateTime.Now.ToShortDateString();
            var seldeptdata = new List<SelectListItem>();
            seldeptdata = sdModel.rtnSysDataList("DeptIndex", "請選擇部門");
            ViewBag.selDeptIndex = seldeptdata;
            var seljobdata = new List<SelectListItem>();
            seljobdata = sdModel.rtnSysDataList("JobIndex", "請選擇職位");
            ViewBag.selJobIndex = seljobdata;
            var seljobclass = new List<SelectListItem>();
            seljobclass = sdModel.rtnSysDataList("JobClass", "請選擇類別");
            ViewBag.selJobClass = seljobclass;
            return View();
        }

        [HttpPost]
        public RedirectResult Create(FormCollection form)
        {
            List<string> DataList = new List<string>();
            DataList.Add(form["hideEmpIndex"].ToString());
            DataList.Add(form["hideDeptIndex"].ToString());
            DataList.Add(form["hideJobIndex"].ToString());
            DataList.Add(form["hideJobDateTime"].ToString());
            DataList.Add(form["hideJobClass"].ToString());
            DataList.Add(form["textJobNotation"].ToString());
            DataList.Add(form["textJobRemark"].ToString());
            DataList.Add(form["hideJobStatus"].ToString());
            DataList.Add(form["hideJobJoinDate"].ToString());
            DataList.Add("");
            string execValue = jdModel.DataCreate(DataList);
            return Redirect("~/EmployeeJobDetail/Index");
        }

        public ActionResult Update(string fEmpIndex, string fDeptIndex, string fJobIndex)
        {
            modelDataClear();
            jobList = jdModel.detailEmployeeJobDetail(fEmpIndex, fDeptIndex, fJobIndex);
            ViewBag.valEmpIndex = fEmpIndex;
            ViewBag.valDeptIndex = fDeptIndex;
            ViewBag.valJobIndex = fJobIndex;
            if (jobList.Count() > 0)
            {
                ViewBag.valEmpName = jobList[0].lEmpName.ToString();
                ViewBag.valDeptTitle = jobList[0].lDeptTitle.ToString();
                ViewBag.valJobTitle = jobList[0].lJobTitle.ToString();
                ViewBag.valJobClass = jobList[0].lJobClass.ToString();
                ViewBag.valJobNotation = jobList[0].lJobNotation.ToString();
                ViewBag.valJobRemark = jobList[0].lJobRemark.ToString();
                ViewBag.valJoinDateTime = jobList[0].lJobDateTime.ToString();
                ViewBag.valJobJoinDate = jobList[0].lJobJoinDate.ToString();
                ViewBag.valJobStatus = jobList[0].lJobStatus.ToString();
                ViewBag.valJobLeaveDate = jobList[0].lJobLeaveDate.ToString();
                ViewBag.valJobClassTitle = jobList[0].lJobClassTitle.ToString();
            }
            ViewBag.valJobLeaveDate = (ViewBag.valJobStatus == "O") ? "" : (ViewBag.valJobLeaveDate != "") ? ViewBag.valJobLeaveDate : System.DateTime.Now.ToShortDateString();
            List<SelectListItem> seljobclass = new List<SelectListItem>();            
            seljobclass = sdModel.rtnSysDataList("JobClass", "請選擇類別");
            //seljobclass.Where(x => x.Value == ViewBag.valJobClass.Trim()).First().Selected = true;
            ViewBag.selJobClass = seljobclass;            
            return View();
        }

        [HttpPost]
        public RedirectResult Update(FormCollection form)
        {
            List<string> DataList = new List<string>();
            DataList.Add(form["hideEmpIndex"].ToString());
            DataList.Add(form["hideDeptIndex"].ToString());
            DataList.Add(form["hideJobIndex"].ToString());
            DataList.Add(form["hideJobDateTime"].ToString());
            DataList.Add(form["hideJobClass"].ToString());
            DataList.Add(form["textJobNotation"].ToString());
            DataList.Add(form["textJobRemark"].ToString());
            DataList.Add(form["hideJobStatus"].ToString());
            DataList.Add(form["hideJobJoinDate"].ToString());
            DataList.Add(form["hideJobLeaveDate"].ToString());
            string execValue = jdModel.DataUpdate(DataList);
            return Redirect("~/EmployeeJobDetail/Index");
        }

        public RedirectResult Delete(string fEmpIndex, string fDeptIndex, string fJobIndex)
        {
            string execValue = jdModel.DataDelete(fEmpIndex, fDeptIndex, fJobIndex);
            return Redirect("~/EmployeeJobDetail/Index");
        }

        public PartialViewResult getBindData(string funSearchValue, string funPageIndex, EmployeeJobDetailModels viewModel)
        {

            jobList = jdModel.reListEmployeeJobDetail();
            if (!(string.IsNullOrWhiteSpace(funSearchValue)))
            {
                jobList = jobList.Where(x => x.lEmpIndex.Contains(funSearchValue)
                || x.lDeptIndex.Contains(funSearchValue) || x.lJobNotation.Contains(funSearchValue)
                || x.lJobRemark.Contains(funSearchValue)).ToList();
            }
            viewModel.ListEmployeeJobDetail = jobList;
            viewModel.valSumDataCount = jobList.Count.ToString();
            viewModel.valPageDataCount = "30";
            viewModel.valSumPageCount = Convert.ToInt32(Math.Ceiling(Convert.ToDecimal(viewModel.valSumDataCount) / Convert.ToDecimal(viewModel.valPageDataCount))).ToString();
            viewModel.valPageIndex = (ViewBag.valPageIndex == null) ? "1" : viewModel.valPageIndex;
            viewModel.valPageIndex = funPageIndex;
            ViewBag.valPageIndex = viewModel.valPageIndex;
            ViewBag.valShowDetail = ViewBag.valPageIndex;
            ViewBag.valSumDataCount = viewModel.valSumDataCount;
            ViewBag.valPageDataCount = viewModel.valPageDataCount;
            ViewBag.valSumPageCount = viewModel.valSumPageCount;
            return PartialView("List", viewModel);
        }

        private void modelDataClear() {
            ViewBag.valEmpIndex = ""; ViewBag.valDeptIndex = ""; ViewBag.valJobIndex = ""; ViewBag.valEmpName = "";
            ViewBag.valDeptTitle = ""; ViewBag.valJobTitle = ""; ViewBag.valJobClass = ""; ViewBag.valJobNotation = "";
            ViewBag.valJobRemark = ""; ViewBag.valJoinDateTime = ""; ViewBag.valJobJoinDate = ""; ViewBag.valJobStatus = "";
            ViewBag.valJobLeaveDate = "";
        }

    }
}

MVCEmp/Views/EmployeeJobDetail/Create.cshtml
@using MVCEmp.Models
@model EmployeeJobDetailModels
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">

    $(function ($) {
        $("#textJobJoinDate").datepicker({ dateFormat: 'yy/mm/dd' });
        $('#selEmpIndex').change(funcSelectEmpChangeHide);
        $('#selDeptIndex').change(funcSelectDeptChangeHide);
        $('#selJobIndex').change(funcSelectJobChangeHide);
        $('#selJobClass').change(funcSelectClassChangeHide);
        $('#btnForm').click(funcFormDataConfirm);
    });

    funcSelectEmpChangeHide = function () {
        var valSelectEmp = $('#selEmpIndex :selected').val();
        $('#hideEmpIndex').val(valSelectEmp);
    }

    funcSelectDeptChangeHide = function () {
        var valSelectDept = $('#selDeptIndex :selected').val();
        $('#hideDeptIndex').val(valSelectDept);
    }

    funcSelectJobChangeHide = function () {
        var valSelectJob = $('#selJobIndex :selected').val();
        $('#hideJobIndex').val(valSelectJob);
    }

    funcSelectClassChangeHide = function () {
        var valSelClass = $('#selJobClass :selected').val();
        $('#hideJobClass').val(valSelClass);
    }

    funcFormDataConfirm = function () {
        if ($('#selDeptIndex :selected').val() == "") {
            $('#showMess').notify("請務必選擇部門!!"); $('#selDeptIndex').focus(); return false;
        } else { $('#hideDeptIndex').val($('#selDeptIndex :selected').val()); }
        if ($('#selJobIndex :selected').val() == "") {
            $('#showMess').notify("請務必選擇職位!!"); $('#selJobIndex').focus(); return false;
        } else { $('#hideJobIndex').val($('#selJobIndex :selected').val()); }
        if ($('#selJobClass :selected').val() == "") {
            $('#showMess').notify("請務必選擇類別!!"); $('#selJobClass').focus(); return false;
        } else { $('#hideJobClass').val($('#selJobClass :selected').val()); }
        if ($('#textJobJoinDate').val() == "") {
            $('#showMess').notify("請務必選擇日期!!"); $('#textJobJoinDate').focus(); return false;
        } else {
            $('#hideJobJoinDate').val($('#textJobJoinDate').val());
        }
        $('#form1').submit();
    }

</script>
@using (Html.BeginForm("Create", "EmployeeJobDetail", FormMethod.Post, new { id = "form1" }))
{
    @Html.Hidden("hideEmpIndex", "")
    @Html.Hidden("hideDeptIndex", "")
    @Html.Hidden("hideJobIndex", "")
    @Html.Hidden("hideJobClass", "")
    @Html.Hidden("hideJobStatus", "O")
    @Html.Hidden("hideJobJoinDate", "")
    @Html.Hidden("hideJobDateTime", (string)ViewBag.valNowDateTime)

    <table style="width:900px; text-align:center; font-size:15px;font-weight:bold" border="0" cellpadding="0" cellspacing="0">
        <tr style="height:40px;font-weight:bold;font-size:24px"><td style="width:100%; text-align:center" colspan="4">新增員工職務<hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">員工選單</td>
            <td style="width:350px; text-align:left">@Html.DropDownList("selEmpIndex", (IEnumerable<SelectListItem>)ViewBag.selEmpData, new { Style = "width:60%;height:35px" })</td>
            <td style="width:100px; text-align:left">類別</td>
            <td style="width:350px; text-align:left">@Html.DropDownList("selJobClass", (IEnumerable<SelectListItem>)ViewBag.selJobClass, new { Style = "width:60%;height:35px" })</td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">所屬部門</td>
            <td style="width:350px; text-align:left">@Html.DropDownList("selDeptIndex", (IEnumerable<SelectListItem>)ViewBag.selDeptIndex, new { style = "width:60%; height:35px" })</td>
            <td style="width:100px; text-align:left">所屬職位</td>
            <td style="width:350px; text-align:left">@Html.DropDownList("selJobIndex", (IEnumerable<SelectListItem>)ViewBag.selJobIndex, new { Style = "width:60%; height:35px" })</td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">備註說明</td>
            <td style="width:800px; text-align:left" colspan="3">@Html.TextArea("textJobNotation", "", 5, 200, new { Style = "width:95%;" })</td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">附註說明</td>
            <td style="width:800px; text-align:left" colspan="3">@Html.TextArea("textJobRemark", "", 5, 200, new { Style = "width:95%;" })</td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">到職日期</td>
            <td style="width:350px; text-align:left">@Html.TextBox("textJobJoinDate", "", new { Style = "width:60%; height:35px" })</td>
            <td style="width:450px" colspan="2"><span id="showMess"></span></td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100%; text-align:center" colspan="4">
                <input type="submit" value="新增員工工作職位" id="btnForm" style="height:35px; width:200px; font-size:17px; font-weight:bold" />
            </td>
        </tr>
    </table>
}

MVCEmp/Views/EmployeeJobDetail/Index.cshtml
@using MVCEmp.Models
@model EmployeeJobDetailModels
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><br /></h2>
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form1" }))
{
    <table style="width:900px; text-align:center" border="0" cellpadding="0" cellspacing="0">
        <tr style="height:35px; color:black">
            <td style="width:700px; text-align:left">
                查詢條件 : @Html.TextBox("searchValue", (string)ViewBag.searchValue, new { Style = "width:550px;height:35px" })                
                <input type="submit" id="btnsubmit" value="查詢" style="width:50px; height:35px" />
            </td>
            <td style="width:200px; text-align:right">@Html.ActionLink("新增員工工作職務", "Create", "EmployeeJobDetail", new { Style = "height:35px; font-size:16px" })</td>
        </tr>
        <tr><td style="width:100%" colspan="2"><hr />@{Html.RenderPartial("List", Model);}</td></tr>
    </table>

}


MVCEmp/Views/EmployeeJobDetail/List.cshtml
@using MVCEmp.Models
@model EmployeeJobDetailModels
@{ Layout = null; }
<script type="text/javascript">
    FormPageFirst = function () { $('#hidePageIndex').val('1'); $('#form1').submit(); }
    FormPageFinal = function () { $('#hidePageIndex').val($('#hidePageCount').val()); $('#form1').submit(); }
    FormPagePrev = function () { $('#hidePageIndex').val($('#hidePageIndex').val() - 1); $('#form1').submit(); }
    FormPageNext = function () { $('#hidePageIndex').val(eval(eval($('#hidePageIndex').val()) + 1)); $('#form1').submit(); }
    FormPageSelect = function (newPageIndex) { $('#hidePageIndex').val(newPageIndex); $('#form1').submit(); }
    confirmDataDelete = function () {
        if (confirm("確定要刪除這筆資料嗎!!")) {
            $('#form1').submit();
        } else { return false;}
    }

</script>

@Html.Hidden("hideDataCount", (string)ViewBag.valSumDataCount)
@Html.Hidden("hideRowPage", (string)ViewBag.valPageDataCount)
@Html.Hidden("hidePageCount", (string)ViewBag.valSumPageCount)
@Html.Hidden("hidePageIndex", (string)ViewBag.valPageIndex)
@{  int DataIndexTop = 0;
  if (Convert.ToInt32(ViewBag.valPageIndex) > 1) { DataIndexTop = Convert.ToInt32(Convert.ToInt32(ViewBag.valPageDataCount) * Convert.ToInt32(Convert.ToInt32(ViewBag.valPageIndex) - 1)); }
  int DataIndexDown = 0;
  if (Convert.ToInt32(ViewBag.valPageIndex) == 1)
  {
      if (Convert.ToInt32(ViewBag.valSumDataCount) < Convert.ToInt32(ViewBag.valPageDataCount))
      {
          DataIndexDown = Convert.ToInt32(ViewBag.valSumDataCount);
      }
      else
      {
          DataIndexDown = Convert.ToInt32(ViewBag.valPageDataCount);
      }
  }
  else
  {
      if (Convert.ToInt32(Convert.ToInt32(ViewBag.valPageDataCount) * Convert.ToInt32(ViewBag.valPageIndex)) > Convert.ToInt32(ViewBag.valSumDataCount))
      {
          DataIndexDown = Convert.ToInt32(ViewBag.valSumDataCount);
      }
      else
      {
          DataIndexDown = Convert.ToInt32(Convert.ToInt32(ViewBag.valPageDataCount) * Convert.ToInt32(ViewBag.valPageIndex));
      }
  }
}
<table style="width:100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td style="width:100%" colspan="10">
            頁數: @ViewBag.valPageIndex 頁 / @ViewBag.valSumPageCount 頁
            <input type="submit" id="PageFirstB" value="第一頁" style="width:70px; height:35px" @if (Convert.ToInt32(ViewBag.valPageIndex) == 1) { @Html.Raw("disabled")      ; } else { @Html.Raw("")      ; @Html.Raw(" onclick='FormPageFirst()'")      ; } />
            <input type="submit" id="PagePrevB" value="上一頁" style="width:70px; height:35px" @if (Convert.ToInt32(ViewBag.valPageIndex) == 1) { @Html.Raw("disabled")      ; } else { @Html.Raw("")      ; @Html.Raw(" onclick='FormPagePrev()'")      ; } />
            <select id="PageSelectB" style="width:70px; height:35px" onchange="FormPageSelect(this.value);">
                @for (int i = 1; i <= Convert.ToInt32((string)ViewBag.valSumPageCount); i++)
                    {
                    <option value="@i.ToString()" @Html.Raw((Convert.ToInt32(ViewBag.valPageIndex) == Convert.ToInt32(i)) ? "selected " : "")>@i.ToString()</option>
                }
            </select>
            <input type="submit" id="PageNextB" value="下一頁" style="width:70px; height:35px" @if (Convert.ToInt32(ViewBag.valPageIndex) == Convert.ToInt32(ViewBag.valSumPageCount)) { @Html.Raw("disabled")      ; } else { @Html.Raw("")      ; @Html.Raw(" onclick='FormPageNext()'")       ; } />
            <input type="submit" id="PageFinalB" value="最末頁" style="width:70px; height:35px" @if (Convert.ToInt32(ViewBag.valPageIndex) == Convert.ToInt32(ViewBag.valSumPageCount)) { @Html.Raw("disabled")      ; } else { @Html.Raw("")      ; @Html.Raw(" onclick='FormPageFinal()'")      ; } />
            資料數: 共 @ViewBag.valSumDataCount 筆 / 每頁 @ViewBag.valPageDataCount 筆  / @DataIndexTop ~ @DataIndexDown
        </td>
    </tr>
    <tr><td style="width:100%" colspan="10"><hr /></td></tr>
    <tr style="height:35px; color:black; font-size:18px">        
        <td style="width:100px; text-align:center">員編</td>
        <td style="width:100px; text-align:center">姓名</td>
        <td style="width:100px; text-align:center">單位</td>
        <td style="width:100px; text-align:center">職位</td>
        <td style="width:100px; text-align:center">類別</td>
        <td style="width:75px; text-align:center">新增日期</td>
        <td style="width:50px; text-align:center">狀態</td>
        <td style="width:75px; text-align:center">取消日期</td>
        <td style="width:100px; text-align:center" colspan="2">更新</td>
    </tr>
    <tr><td style="width:100%" colspan="10"><hr /></td></tr>    
    @for (int i = DataIndexTop; i < DataIndexDown; i++)
    {
        <tr style="height:30px;color:blue;font-size:14px">            
            <td style="width:100px; text-align:center">@Model.ListEmployeeJobDetail[i].lEmpIndex</td>
            <td style="width:100px; text-align:center">@Model.ListEmployeeJobDetail[i].lEmpName</td>
            <td style="width:100px; text-align:center">@Model.ListEmployeeJobDetail[i].lDeptTitle</td>
            <td style="width:100px; text-align:center">@Model.ListEmployeeJobDetail[i].lJobTitle</td>
            <td style="width:100px; text-align:center">@Model.ListEmployeeJobDetail[i].lJobClassTitle</td>
            <td style="width:75px; text-align:center">@Model.ListEmployeeJobDetail[i].lJobJoinDate</td>
            <td style="width:50px; text-align:center">@Model.ListEmployeeJobDetail[i].lJobStatus</td>
            <td style="width:75px; text-align:center">@Model.ListEmployeeJobDetail[i].lJobLeaveDate</td>
            <td style="width:50px; text-align:center">@Ajax.ActionLink("修改", "Update", "EmployeeJobDetail", new { fEmpIndex = Model.ListEmployeeJobDetail[i].lEmpIndex, fDeptIndex = Model.ListEmployeeJobDetail[i].lDeptIndex, fJobIndex = Model.ListEmployeeJobDetail[i].lJobIndex }, new AjaxOptions { HttpMethod = "POST" })</td>
            <td style="width:50px; text-align:center">@Html.ActionLink("刪除", "Delete", "EmployeeJobDetail", new { fEmpIndex = Model.ListEmployeeJobDetail[i].lEmpIndex, fDeptIndex = Model.ListEmployeeJobDetail[i].lDeptIndex, fJobIndex = Model.ListEmployeeJobDetail[i].lJobIndex }, new { onclick = "confirmDataDelete()" })</td>
        </tr>
        <tr><td style="width:100%" colspan="10"><hr /></td></tr>
    }
</table>

MVCEmp/Views/EmployeeJobDetail/Update.cshtml
@using MVCEmp.Models
@model EmployeeJobDetailModels
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">

    $(function ($) {
        $("#textJobLeaveDate").datepicker({ dateFormat: 'yy/mm/dd' });        
        $('#selJobClass option[value=' + $('#hideJobClass').val() + ']').attr('selected', true);    //  將JobClass取得的值被點選
        $('#selJobClass').change(funcSelectClassChangeHide);
        $('#checkJobStatus').click(function () {
            if (this.checked == true) {
                $('#hideJobStatus').val("O");
            } else {
                $('#hideJobStatus').val("X");
            }
        });
        $('#btnForm').click(funcFormDataConfirm);
        
    });

    funcSelectClassChangeHide = function () {
        var valSelClass = $('#selJobClass :selected').val();
        $('#hideJobClass').val(valSelClass);
    }

    funcFormDataConfirm = function () {
        if ($('#selJobClass :selected').val() == "") {
            $('#showMess').notify("請務必選擇類別!!"); $('#selJobClass').focus(); return false;
        } else { $('#hideJobClass').val($('#selJobClass :selected').val()); }
        if ($('#checkJoStatus').checked == false) {
            if ($('#textJobLeaveDate').val() == "") {
                $('#showMess').notify("請務必選擇離職日期!!"); $('#textJobLeaveDate').focus(); return false;
            } else {
                $('#hideJobLeaveDate').val($('#textJobLeaveDate').val());
            }
        }        
        $('#form1').submit();
    }

</script>
<h2>Update</h2>
@using (Html.BeginForm("Update", "EmployeeJobDetail", FormMethod.Post, new { id = "form1" }))
{
    @Html.Hidden("hideEmpIndex", (string)ViewBag.valEmpIndex)
    @Html.Hidden("hideDeptIndex", (string)@ViewBag.valDeptIndex)
    @Html.Hidden("hideJobIndex", (string)@ViewBag.valJobIndex)
    @Html.Hidden("hideJobClass", (string)@ViewBag.valJobClass)
    @Html.Hidden("hideJobStatus", (string)@ViewBag.valJobStatus)
    @Html.Hidden("hideJobJoinDate", (string)@ViewBag.valJobJoinDate)
    @Html.Hidden("hideJobDateTime", (string)@ViewBag.valJoinDateTime)
    @Html.Hidden("hideJobLeaveDate", (string)@ViewBag.valJobLeaveDate)
    <table style="width:900px; text-align:center; font-size:15px;font-weight:bold" border="0" cellpadding="0" cellspacing="0">
        <tr style="height:40px;font-weight:bold;font-size:24px"><td style="width:100%; text-align:center" colspan="4">修改員工工作職務<hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">員工編號</td>
            <td style="width:350px; text-align:left">@ViewBag.valEmpIndex</td>
            <td style="width:100px; text-align:left">員工姓名</td>
            <td style="width:350px; text-align:left">@ViewBag.valEmpName</td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">所屬部門</td>
            <td style="width:350px; text-align:left">@ViewBag.valDeptTitle</td>
            <td style="width:100px; text-align:left">所屬職位</td>
            <td style="width:350px; text-align:left">@ViewBag.valJobTitle</td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">類別</td>
            <td style="width:350px; text-align:left">@Html.DropDownList("selJobClass", (IEnumerable<SelectListItem>)ViewBag.selJobClass, new { Style = "width:90%;height:35px" })</td>
            <td style="width:100px; text-align:left">在職狀態</td>
            <td style="width:350px; text-align:left">@Html.CheckBox("checkJobStatus", (ViewBag.valJobStatus == "O") ? true : false)仍在職</td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">備註說明</td>
            <td style="width:800px; text-align:left" colspan="3">@Html.TextArea("textJobNotation", (string)ViewBag.valJobNotation, 5, 200, new { Style = "width:95%;" })</td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">附註說明</td>
            <td style="width:800px; text-align:left" colspan="3">@Html.TextArea("textJobRemark", (string)ViewBag.valJobRemark, 5, 200, new { Style = "width:95%;" })</td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100px; text-align:left">離職日期</td>
            <td style="width:350px; text-align:left">@Html.TextBox("textJobLeaveDate", (string)ViewBag.valJobLeaveDate, new { Style = "width:90%; height:35px" })</td>
            <td style="width:450px" colspan="2"><span id="showMess"></span></td>
        </tr>
        <tr><td style="width:100%;" colspan="4"><hr /></td></tr>
        <tr style="height:35px">
            <td style="width:100%; text-align:center" colspan="4">
                <input type="submit" value="更新工作職位資料" id="btnForm" style="height:35px; width:200px; font-size:17px; font-weight:bold" />
            </td>
        </tr>
    </table>

}