MVCEmp/Controllers/EmployeeDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.IO;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;
using NPOI.SS.UserModel;
using MVCEmp.Models;


namespace MVCEmp.Controllers
{
    public class EmployeeDetailController : Controller
    {
        EmployeeDetailModels edModel = new EmployeeDetailModels();
        SystemDetailModels sdModel = new SystemDetailModels();
        App_Start.ClassDataBase dbClass = new App_Start.ClassDataBase();

        // GET: EmployeeDetail
        public ActionResult Index(EmployeeDetailModels viewModel)
        {
            GetBindData("", "1", viewModel);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Index(FormCollection form, EmployeeDetailModels viewModel)
        {
            string funSearchValue = form["searchValue"].ToString();
            string funPageIndex = form["hidePageIndex"].ToString();
            GetBindData(funSearchValue, funPageIndex, viewModel);
            return View(viewModel);
        }

        public PartialViewResult GetBindData(string funSearchValue, string funPageIndex, EmployeeDetailModels viewModel)
        {
            List<listEmployeeDetail> empList = new List<listEmployeeDetail>();
            empList = edModel.ReListEmployeeDetail();
            if (!(string.IsNullOrWhiteSpace(funSearchValue)))
            {
                empList = empList.Where(x => x.lEmpIndex.Contains(funSearchValue) || x.lEmpName.Contains(funSearchValue)
                || x.lEmpEmail.Contains(funSearchValue) || x.lEmpMobile.Contains(funSearchValue)
                || x.lEmpPhone.Contains(funSearchValue) || x.lEmpNotation.Contains(funSearchValue)
                || x.lEmpRemark.Contains(funSearchValue) || x.lEmpJoinDate.Contains(funSearchValue)
                || x.lEmpLeaveDate.Contains(funSearchValue)).ToList();
            }
            viewModel.listEmployeeDetail = empList;
            viewModel.valSumDataCount = empList.Count.ToString();
            viewModel.valPageDataCount = "30";
            viewModel.valSumPageCount = Convert.ToInt32(Math.Ceiling(Convert.ToDecimal(viewModel.valSumDataCount) / Convert.ToDecimal(viewModel.valPageDataCount))).ToString();
            viewModel.valPageIndex = (ViewBag.valPageIndex == null) ? "1" : viewModel.valPageIndex;
            viewModel.valPageIndex = funPageIndex;
            ViewBag.valPageIndex = viewModel.valPageIndex;
            ViewBag.valShowDetail = ViewBag.valPageIndex;
            ViewBag.valSumDataCount = viewModel.valSumDataCount;
            ViewBag.valPageDataCount = viewModel.valPageDataCount;
            ViewBag.valSumPageCount = viewModel.valSumPageCount;
            return PartialView("List", viewModel);
        }

        public ActionResult Create()
        {
            List<SelectListItem> sysSelAreaCity = new List<SelectListItem>();
            sysSelAreaCity = sdModel.rtnSysDataList("addresscity", "請選擇城市");
            ViewBag.selAreaCity = sysSelAreaCity;
            List<SelectListItem> sysSelZipArea = new List<SelectListItem>();
            sysSelZipArea = sdModel.rtnSysDataList("","請選擇區域");
            ViewBag.selAreaZip = sysSelZipArea;
            return View();
        }

        [HttpPost]
        public  RedirectResult Create(FormCollection form)
        {
            List<string> listCreateData = new List<string>();
            listCreateData.Add(edModel.returnMaxEmpIndex().ToString());
            listCreateData.Add(form["textEmpID"].ToString());
            listCreateData.Add(form["textEmpName"].ToString());
            listCreateData.Add(form["hideEmpSex"].ToString());
            listCreateData.Add(form["textEmpEmail"].ToString());
            listCreateData.Add(form["textEmpAddress"].ToString());
            listCreateData.Add(form["textEmpMobile"].ToString());
            listCreateData.Add(form["textEmpPhone"].ToString());
            listCreateData.Add(form["textEmpNotation"].ToString());
            listCreateData.Add(form["textEmpRemark"].ToString());
            listCreateData.Add("O");
            listCreateData.Add(form["textEmpJoinDate"].ToString());
            listCreateData.Add("");
            listCreateData.Add(form["textEmpID"].ToString().Substring(0,6));            
            string returnExecValue = edModel.DataCreate(listCreateData);            
            return Redirect("~/EmployeeDetail/Index");
        }

        public ActionResult Update(string vIndex)
        {
            ViewBag.valEmpIndex = vIndex.ToString();
            List<listEmployeeDetail> empDetail = new List<listEmployeeDetail>();
            empDetail = edModel.ReListEmployeeDetail().Where(x => x.lEmpIndex == vIndex.ToString()).ToList();
            if (empDetail.Count > 0)
            {
                ViewBag.valEmpName = empDetail[0].lEmpName.ToString();
                ViewBag.valEmpID = empDetail[0].lEmpID.ToString();
                ViewBag.valEmpSex = empDetail[0].lEmpSex.ToString();
                ViewBag.valEmpMobile = empDetail[0].lEmpMobile.ToString();
                ViewBag.valEmpPhone = empDetail[0].lEmpPhone.ToString();
                ViewBag.valEmpEmail = empDetail[0].lEmpEmail.ToString();
                ViewBag.valEmpAddress = empDetail[0].lEmpAddress.ToString();
                ViewBag.valEmpNotation = empDetail[0].lEmpNotation.ToString();
                ViewBag.valEmpRemark = empDetail[0].lEmpRemark.ToString();
                ViewBag.valEmpStatus = empDetail[0].lEmpStatus.ToString();
                ViewBag.valEmpJoinDate = empDetail[0].lEmpJoinDate.ToString();
                ViewBag.valEmpLeaveDate = empDetail[0].lEmpLeaveDate.ToString();
            }
            return View();
        }

        [HttpPost]
        public RedirectResult Update(FormCollection form)
        {
            List<string> listUpdateData = new List<string>();
            listUpdateData.Add(form["hideEmpIndex"].ToString());
            listUpdateData.Add(form["hideEmpID"].ToString());
            listUpdateData.Add(form["textEmpName"].ToString());
            listUpdateData.Add(form["hideEmpSex"].ToString());
            listUpdateData.Add(form["textEmpEmail"].ToString());
            listUpdateData.Add(form["textEmpAddress"].ToString());
            listUpdateData.Add(form["textEmpMobile"].ToString());
            listUpdateData.Add(form["textEmpPhone"].ToString());
            listUpdateData.Add(form["textEmpNotation"].ToString());
            listUpdateData.Add(form["textEmpRemark"].ToString());
            listUpdateData.Add(form["hideEmpStatus"].ToString());
            listUpdateData.Add(form["hideEmpJoinDate"].ToString());
            listUpdateData.Add(form["textEmpLeaveDate"].ToString());
            string showData = "";
            for (int i = 0; i < listUpdateData.Count; i++)
            {
                showData += string.Format(@"{0}<br>", listUpdateData[i].ToString());
            }
            string returnExecValue = edModel.DataUpdate(listUpdateData);
            return Redirect("~/EmployeeDetail/Index");
        }

        [HttpPost]
        public void OutExcelData()
        {
            string ExportFileName = "EmpData.xlsx"; string ExportFileTitle = "Data"; Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            XSSFWorkbook NpoiWB = new XSSFWorkbook();
            XSSFCellStyle xCellStyle = (XSSFCellStyle)NpoiWB.CreateCellStyle();
            XSSFDataFormat NpoiFormat = (XSSFDataFormat)NpoiWB.CreateDataFormat();
            xCellStyle.SetDataFormat(NpoiFormat.GetFormat("[DbNum2][$-804]0"));
            XSSFCellStyle cellStyleFontColor = (XSSFCellStyle)NpoiWB.CreateCellStyle();
            XSSFFont font1 = (XSSFFont)NpoiWB.CreateFont(); font1.Color = (short)10; font1.IsBold = true;
            cellStyleFontColor.SetFont(font1);
            ///     進行產生Excel檔案流程
            ISheet xSheet = NpoiWB.CreateSheet(ExportFileTitle);
            List<string> listColumn = edModel.listEmployeeColumn;
            ///     建立標題列
            IRow xRowT = xSheet.CreateRow(0); xRowT.HeightInPoints = 40;
            for (int i = 0; i < listColumn.Count; i++) { ICell xCellT = xRowT.CreateCell(i); xCellT.SetCellValue(listColumn[i]); }
            ///     讀取資料庫資料
            List<listEmployeeDetail> ListEmpData = new List<listEmployeeDetail>();
            ListEmpData = edModel.ReListEmployeeDetail();
            if (ListEmpData != null && ListEmpData.Count > 0)
            {
                for (int i = 0; i < ListEmpData.Count; i++)
                {
                    listEmployeeDetail item = ListEmpData[i];
                    List<string> list = new List<string>();
                    list.Add(item.lEmpIndex.ToString());
                    list.Add(item.lEmpName.ToString());
                    list.Add(item.lEmpSex.ToString());
                    list.Add(item.lEmpEmail.ToString());
                    list.Add(item.lEmpAddress.ToString());
                    list.Add(item.lEmpMobile.ToString());
                    list.Add(item.lEmpPhone.ToString());
                    list.Add(item.lEmpNotation.ToString());
                    list.Add(item.lEmpRemark.ToString());
                    list.Add(item.lEmpStatus.ToString());
                    list.Add(item.lEmpJoinDate.ToString());
                    list.Add(item.lEmpLeaveDate.ToString());
                    IRow xRowD = xSheet.CreateRow(i + 1); xRowD.HeightInPoints = 30;
                    for (int b = 0; b < list.Count; b++) { ICell xCellData = xRowD.CreateCell(b); xCellData.SetCellValue(list[b]); }
                }

            }
            MemoryStream MS = new MemoryStream(); NpoiWB.Write(MS);

MVCEmp/Views/EmployeeDetail/List.cshtml
@{
    Layout = null;
}
<script type="text/javascript">

    FormPageFirst = function () { $('#hidePageIndex').val('1'); $('#form1').submit(); }
    FormPageFinal = function () { $('#hidePageIndex').val($('#hidePageCount').val()); $('#form1').submit(); }
    FormPagePrev = function () { $('#hidePageIndex').val($('#hidePageIndex').val() - 1); $('#form1').submit(); }
    FormPageNext = function () { $('#hidePageIndex').val(eval(eval($('#hidePageIndex').val()) + 1)); $('#form1').submit(); }
    FormPageSelect = function (newPageIndex) { $('#hidePageIndex').val(newPageIndex); $('#form1').submit(); }

</script>

@Html.Hidden("hideDataCount", (string)ViewBag.valSumDataCount)
@Html.Hidden("hideRowPage", (string)ViewBag.valPageDataCount)
@Html.Hidden("hidePageCount", (string)ViewBag.valSumPageCount)
@Html.Hidden("hidePageIndex", (string)ViewBag.valPageIndex)
@{  int DataIndexTop = 0;
  if (Convert.ToInt32(ViewBag.valPageIndex) > 1) { DataIndexTop = Convert.ToInt32(Convert.ToInt32(ViewBag.valPageDataCount) * Convert.ToInt32(Convert.ToInt32(ViewBag.valPageIndex) - 1)); }
  int DataIndexDown = 0;
  if (Convert.ToInt32(ViewBag.valPageIndex) == 1)
  {
      if (Convert.ToInt32(ViewBag.valSumDataCount) < Convert.ToInt32(ViewBag.valPageDataCount))
      {
          DataIndexDown = Convert.ToInt32(ViewBag.valSumDataCount);
      }
      else
      {
          DataIndexDown = Convert.ToInt32(ViewBag.valPageDataCount);
      }
  }
  else
  {
      if (Convert.ToInt32(Convert.ToInt32(ViewBag.valPageDataCount) * Convert.ToInt32(ViewBag.valPageIndex)) > Convert.ToInt32(ViewBag.valSumDataCount))
      {
          DataIndexDown = Convert.ToInt32(ViewBag.valSumDataCount);
      }
      else
      {
          DataIndexDown = Convert.ToInt32(Convert.ToInt32(ViewBag.valPageDataCount) * Convert.ToInt32(ViewBag.valPageIndex));
      }
  }
}
<table style="width:100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td style="width:100%" colspan="9">
            頁數: @ViewBag.valPageIndex 頁 / @ViewBag.valSumPageCount 頁
            <input type="submit" id="PageFirst" value="第一頁" style="width:70px; height:35px" @if (Convert.ToInt32(ViewBag.valPageIndex) == 1) { @Html.Raw("disabled")      ; } else { @Html.Raw("")      ; @Html.Raw(" onclick='FormPageFirst()'")      ; } />
            <input type="submit" id="PagePrev" value="上一頁" style="width:70px; height:35px" @if (Convert.ToInt32(ViewBag.valPageIndex) == 1) { @Html.Raw("disabled")      ; } else { @Html.Raw("")      ; @Html.Raw(" onclick='FormPagePrev()'")      ; } />
            <select id="PageSelect" style="width:70px; height:35px" onchange="FormPageSelect(this.value);">
                @for (int i = 1; i <= Convert.ToInt32((string)ViewBag.valSumPageCount); i++)
                    {
                    <option value="@i.ToString()" @Html.Raw((Convert.ToInt32(ViewBag.valPageIndex) == Convert.ToInt32(i)) ? "selected " : "")>@i.ToString()</option>
                }
            </select>
            <input type="submit" id="PageNext" value="下一頁" style="width:70px; height:35px" @if (Convert.ToInt32(ViewBag.valPageIndex) == Convert.ToInt32(ViewBag.valSumPageCount)) { @Html.Raw("disabled")      ; } else { @Html.Raw("")      ; @Html.Raw(" onclick='FormPageNext()'")       ; } />
            <input type="submit" id="PageFinal" value="最末頁" style="width:70px; height:35px" @if (Convert.ToInt32(ViewBag.valPageIndex) == Convert.ToInt32(ViewBag.valSumPageCount)) { @Html.Raw("disabled")      ; } else { @Html.Raw("")      ; @Html.Raw(" onclick='FormPageFinal()'")      ; } />
            資料數: 共 @ViewBag.valSumDataCount 筆 / 每頁 @ViewBag.valPageDataCount 筆  / @DataIndexTop ~ @DataIndexDown
        </td>
    </tr>
    <tr><td style="width:100%" colspan="9"><hr /></td></tr>
    <tr style="height:35px; font-size:18px; background-color:blue; color:white">        
        <td style="width:100px; text-align:center">員編<br />就職日期</td>
        <td style="width:100px; text-align:center">姓名</td>
        <td style="width:100px; text-align:center">行動電話<br />連絡電話</td>
        <td style="width:300px; text-align:center">電子郵件<br />聯絡地址</td>
        <td style="width:100px; text-align:center">備註<br />附註說明</td>
        <td style="width:100px; text-align:center">狀態<br />離職日期</td>
        <td style="width:100px; text-align:center" colspan="2">更新</td>
    </tr>
    <tr><td style="width:100%" colspan="9"><hr /></td></tr>    
    @for (int i = DataIndexTop; i < DataIndexDown; i++)
    {
        <tr style="height:30px;color:blue;font-size:14px">            
            <td style="width:100px; text-align:center">@Model.listEmployeeDetail[i].lEmpIndex<br />@Model.listEmployeeDetail[i].lEmpJoinDate</td>
            <td style="width:100px; text-align:center">@Model.listEmployeeDetail[i].lEmpName</td>
            <td style="width:100px; text-align:left">@Model.listEmployeeDetail[i].lEmpMobile<br />@Model.listEmployeeDetail[i].lEmpPhone</td>
            <td style="width:300px; text-align:left">@Model.listEmployeeDetail[i].lEmpEmail<br />@Model.listEmployeeDetail[i].lEmpAddress</td>
            <td style="width:100px; text-align:left">@Model.listEmployeeDetail[i].lEmpNotation<br />@Model.listEmployeeDetail[i].lEmpRemark</td>
            <td style="width:100px; text-align:center">@Model.listEmployeeDetail[i].lEmpStatus<br />@Model.listEmployeeDetail[i].lEmpLeaveDate</td>
            <td style="width:50px; text-align:center">@Html.ActionLink("修改", "Update", "EmployeeDetail", new { vIndex = Model.listEmployeeDetail[i].lEmpIndex }, new AjaxOptions { HttpMethod = "Post" })</td>
            <td style="width:50px; text-align:center">@Html.ActionLink("刪除", "Delete", "EmployeeDetail", new { vIndex = Model.listEmployeeDetail[i].lEmpIndex }, new AjaxOptions { HttpMethod = "Post" })</td>
        </tr>
        <tr><td style="width:100%" colspan="9"><hr /></td></tr>
    }
</table>


MVCEmp/Views/EmployeeDetail/Update.cshtml
@using MVCEmp.Models
@model EmployeeDetailModels
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Update</h2>
<script type="text/javascript">

    var baseUrl = '@Html.Raw(Url.Content("~"))';
    if (baseUrl == '/') { baseUrl = ''; }

    $(function ($) {
        $('input:radio[name="radioEmpSex"]').change(FormRadioChecked);
        $('input:checkbox[name="checkEmpStatus"]').change(FormCheckBoxChecked);
        $('#textEmpLeaveDate').datepicker({ dateFormat: "yy/mm/dd" });
        $('#btnForm').click(FormDataCheck);
    });

    FormRadioChecked = function () {
        if ($(this).is(':checked') && $(this).val() == 'M') {
            $('#hideEmpSex').val('M');
        } else { $('#hideEmpSex').val('F'); }
    }

    FormCheckBoxChecked = function () {
        if ($(this).is(':checked')) {
            $('#hideEmpStatus').val('O');
            $('#textEmpLeaveDate').val("");
        } else {
            $('#hideEmpStatus').val('X');
            if ($('#textEmpLeaveDate').val() == "") {
                $('#showMess').notify("在職狀態已被取消!!請務必填寫離職日期!!");
                $('#textEmpLeaveDate').focus();
            }
        }
    }

    FormDataCheck = function () {
        if ($('#textEmpName').val() == "") { $('#showMess').notify('員工姓名不得空白'); $('#textEmpName').focus(); return false; }
        if ($('#textEmpMobile').val() == "") { $('#showMess').notify('行動電話不得空白'); $('#textEmpMobile').focus(); return false; }
        if ($('#textEmpEmail').val() == "") { $('#showMess').notify('電子郵件不得空白'); $('#textEmpEmail').focus(); return false; }
        if ($('#textEmpAddress').val() == "") { $('#showMess').notify('聯絡地址不得空白'); $('#textEmpAddress').focus(); return false; }
        if ($('input:checkbox[name="checkEmpStatus"]').is(':checked')) {
            $('#hideEmpSex').val('M');
            $('#textEmpLeaveDate').val("");
        } else {
            $('#hideEmpSex').val('F');
            if ($('#textEmpLeaveDate').val() == "") {
                $('#showMess').notify("在職狀態已被取消!!請務必填寫離職日期!!");
                $('#textEmpLeaveDate').focus();
                return false;
            }
        }
    }


</script>
@using (Html.BeginForm("Update", "EmployeeDetail", FormMethod.Post, new { id = "form1" }))
{

    @Html.Hidden("hideEmpIndex", (string)ViewBag.valEmpIndex)
    @Html.Hidden("hideEmpID", (string)ViewBag.valEmpID)
    @Html.Hidden("hideEmpSex", (string)ViewBag.valEmpSex)
    @Html.Hidden("hideEmpStatus", (string)ViewBag.valEmpStatus)
    @Html.Hidden("hideEmpJoinDate", (string)ViewBag.valEmpJoinDate)
    @ViewBag.showEmpNotation
    <table style="width:900px" border="0" cellpadding="0" cellspacing="0">
        <tr style="height:40px;font-weight:bold;font-size:24px"><td style="width:100%; text-align:center" colspan="4">修改員工基本資料</td></tr>
        <tr style="height:40px;">
            <td style="width:100px; text-align:left">員工姓名</td>
            <td style="width:350px; text-align:left">@Html.TextBox("textEmpName", (string)ViewBag.valEmpName, new { Style = "width:80%; height:30px" }) </td>
            <td style="width:100px; text-align:left">身分證號</td>
            <td style="width:350px; text-align:left">@ViewBag.valEmpID</td>
        </tr>
        <tr><td colspan="4"><hr /></td></tr>
        <tr style="height:40px;">
            <td style="width:100px; text-align:left;font-weight:bold">員工性別</td>
            <td style="width:350px; text-align:left">
                @Html.RadioButton("radioEmpSex", "M", ((string)ViewBag.valEmpSex == "M") ? true : false)男
                @Html.RadioButton("radioEmpSex", "F", ((string)ViewBag.valEmpSex == "F") ? true : false)女                
            </td>
            <td style="width:100px; text-align:left;font-weight:bold">在職狀態<br />離職日期</td>
            <td style="width:350px; text-align:left">
                @Html.CheckBox("checkEmpStatus", ((string)ViewBag.valEmpStatus == "O") ? true : false)仍在職 到職日期: @ViewBag.valEmpJoinDate<br />
                @Html.TextBox("textEmpLeaveDate", (string)ViewBag.valEmpLeaveDate, new { Style = "width:80%; height:25px" })                
            </td>
        </tr>
        <tr><td colspan="4"><hr /></td></tr>
        <tr style="height:40px;">
            <td style="width:100px; text-align:left">行動電話</td>
            <td style="width:350px; text-align:left">@Html.TextBox("textEmpMobile", (string)ViewBag.valEmpMobile, new { Style = "width:80%; height:30px" }) </td>
            <td style="width:100px; text-align:left">連絡電話</td>
            <td style="width:350px; text-align:left">@Html.TextBox("textEmpPhone", (string)ViewBag.valEmpPhone, new { Style = "width:80%; height:30px" })  </td>
        </tr>
        <tr><td colspan="4"><hr /></td></tr>
        <tr style="height:40px;">
            <td style="width:100px; text-align:left">電子郵件</td>
            <td style="width:800px; text-align:left" colspan="3">@Html.TextBox("textEmpEmail", (string)ViewBag.valEmpEmail, new { Style = "width:95%; height:30px" }) </td>
        </tr>
        <tr><td colspan="4"><hr /></td></tr>
        <tr style="height:40px;">
            <td style="width:100px; text-align:left">聯絡地址</td>
            <td style="width:800px; text-align:left" colspan="3">@Html.TextBox("textEmpAddress", (string)ViewBag.valEmpAddress, new { Style = "width:95%; height:30px" }) </td>
        </tr>
        <tr><td colspan="4"><hr /></td></tr>
        <tr style="height:40px;">
            <td style="width:100px; text-align:left">備註說明</td>
            <td style="width:800px; text-align:left" colspan="3">@Html.TextArea("textEmpNotation", (string)ViewBag.valEmpNotation, 5, 800, new { Style = "width:95%;" }) </td>
        </tr>
        <tr><td colspan="4"><hr /></td></tr>
        <tr style="height:40px;">
            <td style="width:100px; text-align:left">其他說明</td>
            <td style="width:800px; text-align:left" colspan="3">@Html.TextArea("textEmpRemark", (string)ViewBag.valEmpRemark, 5, 800, new { Style = "width:95%;" }) </td>
        </tr>
        <tr><td colspan="4"><hr /><span id="showMess" /></td></tr>
        <tr style="height:40px">
            <td style="width:100%; text-align:center" colspan="4">
                <input type="submit" value="修改員工基本資料" id="btnForm" style="height:35px; width:200px; font-size:17px; font-weight:bold" />
            </td>
        </tr>
    </table>
}

MVCEmp/Views/EmployeeDetail/index.cshtml
@using MVCEmp.Models
@model EmployeeDetailModels
@{
    ViewBag.Title = "index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Index", "EmployeeDetail", FormMethod.Post, new { id = "form1", enctype = "multipart/form-data" }))
{
    <table style="width:900px; text-align:center" border="0" cellpadding="0" cellspacing="0">
        <tr style="height:40px;font-size:20px;font-weight:bold"><td style="width:100%; text-align:center" colspan="4">員工基本資料檔<hr /></td></tr>
        <tr style="height:35px; color:black">
            <td style="width:800px; text-align:left">
                關鍵字 : @Html.TextBox("searchValue", (string)ViewBag.searchValue, new { Style = "width:600px; height:35px" })
                <input type="submit" id="btnsubmit" value="查詢" style="width:100px; height:30px;font-weight:bold;font-size:18px" />
            </td>
            <td style="width:100px; text-align:right">@Html.ActionLink("新增員工資料", "Create", "EmployeeDetail", new { Style = "height:35px; font-size:16px" })</td>
        </tr>
        <tr><td style="width:100%" colspan="4"><hr /></td></tr>
        <tr><td style="width:100%" colspan="4">@{Html.RenderPartial("List", Model);}</td></tr>
    </table>
}